In [12]:
import pandas as pd 
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import numpy as np

In [5]:
src_data = pd.read_csv('open/train.csv',encoding='UTF-8')


In [6]:
value_counts_all = src_data.apply(pd.Series.unique)
print(value_counts_all)

ID          [TRAIN_0000, TRAIN_0001, TRAIN_0002, TRAIN_000...
SUBCLASS    [KIPAN, SARC, SKCM, KIRC, GBMLGG, STES, BRCA, ...
A2M         [WT, R895R, E1462K, K289T, I175F, D533D, L903L...
AAAS        [WT, P130H, L517I, L395P, Q456fs, S228C, S205N...
AADAT       [WT, S27N, N130D, E66K, H287L, M33I, T8M, W86L...
                                  ...                        
ZNRF4       [WT, S219S, P117L, I184S E181A, K171K, A385V, ...
ZPBP        [WT, E254D, P245T, F303V, H335Y E275D, R280C, ...
ZW10        [WT, E529G, A56V, G666G, D406G, E336D, T353A, ...
ZWINT       [WT, E5G, V152V, D83N, G193E, E31Q, T115I, Q26...
ZYX         [WT, S258A, A191V, P38L, V524A, P121P, P260T, ...
Length: 4386, dtype: object


In [50]:
src_data['SUBCLASS'].unique()

array(['KIPAN', 'SARC', 'SKCM', 'KIRC', 'GBMLGG', 'STES', 'BRCA', 'THCA',
       'LIHC', 'HNSC', 'PAAD', 'OV', 'PRAD', 'UCEC', 'LAML', 'COAD',
       'ACC', 'LGG', 'LUSC', 'LUAD', 'CESC', 'PCPG', 'THYM', 'BLCA',
       'TGCT', 'DLBC'], dtype=object)

In [98]:
new_data = src_data[src_data['SUBCLASS']=='KIPAN']

In [147]:
new_data.iloc[0,23]

AttributeError: 'str' object has no attribute 'colunms'

In [153]:
new_data.columns[2]

'A2M'

In [100]:
test = new_data.to_numpy()

In [132]:
test[:,2:]

array([['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ...,
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT']], dtype=object)

In [111]:
KIPAN=test[:,2:]

array([['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ...,
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT'],
       ['WT', 'WT', 'WT', ..., 'WT', 'WT', 'WT']], dtype=object)

In [112]:
i=np.where(KIPAN!='WT')

In [138]:
i

(array([  0,   0,   0, ..., 514, 514, 514], dtype=int64),
 array([  21,  110,  673, ..., 3105, 3282, 3500], dtype=int64))

In [142]:
x=i[0]

In [157]:
np.unique(x)

array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [143]:
y= i[1]+2

In [144]:
x[0]

0

In [145]:
KIPAN[0,21]

'D623D'

In [155]:
for z in range(len(x)):
    print(new_data.columns[x[z]+2],':',new_data.iloc[x[z],y[z]])

A2M : D623D
A2M : F736C
A2M : P117R
A2M : R305S
A2M : N23K
A2M : L192V
A2M : G592G
A2M : K277K
A2M : A699T
A2M : L111L
A2M : I136M
A2M : A219T
A2M : E237*
A2M : A746D
A2M : D465D
A2M : N1445D
A2M : T218T
A2M : G764G
A2M : E660Q
A2M : E291A
A2M : I382M
A2M : V412A
A2M : P222R
A2M : R104H
A2M : P17R
AAAS : C886G
AAAS : S332S
AAAS : V80M
AAAS : E73V
AAAS : N701Y
AAAS : G712S
AAAS : G185*
AAAS : E379fs
AAAS : P4L
AAAS : R735H
AAAS : M18I
AAAS : E4243*
AAAS : E3871D
AAAS : Q6554R
AAAS : V2461V
AAAS : P139H
AAAS : D590A
AADAT : V74fs
AARS1 : R11fs
AARS1 : H1816P
AARS1 : K716N
AARS1 : M1020R
AARS1 : L143P
AARS1 : L413L
AARS1 : P140S
AARS1 : A571A
AARS1 : L4483L
AARS1 : E514*
AARS1 : I68N
AARS1 : E682Q
AARS1 : A432V
AARS1 : M217K
AARS1 : I742F
AARS1 : Y548fs
AARS1 : T366I
AARS1 : R168G
AARS1 : L960L
AARS1 : S1103N
AARS1 : R289W
AARS1 : E236E
AARS1 : F136V
AARS1 : S388S
ABCA1 : R711H
ABCA1 : K111R
ABCA1 : V1376I
ABCA1 : R2060R
ABCA1 : R811Q
ABCA1 : G73G
ABCA1 : I298T
ABCA1 : E150K
ABCA1 : V165M

In [57]:
y = pd.Series(x[i])

In [58]:
y

0        D623D
1        F736C
2        P117R
3        R305S
4         N23K
         ...  
8257     V395V
8258    K1249K
8259     R257S
8260     C278R
8261     K260N
Length: 8262, dtype: object