# 한국어 BERT

In [1]:
!pip install tf_keras

^C


  Using cached tf_keras-2.17.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached tensorflow-2.17.0-cp312-cp312-win_amd64.whl.metadata (3.2 kB)
  Using cached tensorflow_intel-2.17.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached ml_dtypes-0.4.0-cp312-cp312-win_amd64.whl.metadata (20 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached grpcio-1.66.1-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
  Using cached tensorboard-2.17.1-py3-none-any.whl.metadata (1.6 kB)
  Us

In [1]:
from transformers import FillMaskPipeline
from transformers import TFBertForMaskedLM, AutoTokenizer
MODEL_NAME = 'klue/bert-base'
model = TFBertForMaskedLM.from_pretrained(MODEL_NAME, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)


In [2]:
MODEL_NAME = 'klue/bert-base'
model = TFBertForMaskedLM.from_pretrained(MODEL_NAME, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

config.json:   0%|          | 0.00/425 [00:00<?, ?B/s]

c:\Users\humming\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\humming\.cache\huggingface\hub\models--klue--bert-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


pytorch_model.bin:   0%|          | 0.00/445M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


tokenizer_config.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/248k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/495k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

c:\Users\humming\anaconda3\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [3]:
# 스페셜 토큰 값 확인
print('start:',tokenizer.cls_token_id)
print('end:',tokenizer.sep_token_id)
print('mask',tokenizer.mask_token_id)

start: 2
end: 3
mask 4


In [9]:
# BERT는 [MASK]라는 빈칸을 예측하는데 특화되어 있습니다.
text = '신창섭은 [MASK]다.'
inputs = tokenizer(text, return_tensors='tf')

In [5]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[    2, 26846,  2474,  2073,     4,     3]])>, 'token_type_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]])>}

In [6]:
print(inputs['input_ids'])

tf.Tensor([[    2 26846  2474  2073     4     3]], shape=(1, 6), dtype=int32)


In [7]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


In [10]:
pip(text)

[{'score': 0.03692515566945076,
  'token': 3614,
  'token_str': '아니',
  'sequence': '신창섭은 아니 다.'},
 {'score': 0.019316229969263077,
  'token': 4311,
  'token_str': '그대로',
  'sequence': '신창섭은 그대로 다.'},
 {'score': 0.01776396855711937,
  'token': 1902,
  'token_str': '했',
  'sequence': '신창섭은 했 다.'},
 {'score': 0.014043480157852173,
  'token': 1504,
  'token_str': '이',
  'sequence': '신창섭은 이 다.'},
 {'score': 0.013894741423428059,
  'token': 1415,
  'token_str': '없',
  'sequence': '신창섭은 없 다.'}]